export type Product = {
  id: string;
  name: string;
  price: number;
};

export const products: Product[] = [
  { id: "abokado", name: "樹上アボカド", price: 680 },
  { id: "burokkori", name: "畑ブロッコリー", price: 390 },
  { id: "endoumame", name: "朝露えんどう豆", price: 520 },
  { id: "jagaimo", name: "新じゃがいも", price: 420 },
  { id: "jkdj", name: "泥つき生姜", price: 520 },
  { id: "kiui", name: "完熟キウイ", price: 620 },
  { id: "klek", name: "グリーンパプリカ", price: 460 },
  { id: "kokonatu", name: "ココナッツ", price: 980 },
  { id: "konsai", name: "紫根菜ミックス", price: 480 },
  { id: "kyuuri", name: "みずみずしい胡瓜", price: 320 },
  { id: "mango", name: "完熟マンゴー", price: 1480 },
  { id: "midori", name: "高原白菜", price: 430 },
  { id: "momo", name: "香り桃", price: 1280 },
  { id: "nasubi", name: "艶なす", price: 360 },
  { id: "neshouga", name: "新しょうが", price: 450 },
  { id: "ninjin", name: "土付き人参", price: 380 },
  { id: "ninniku", name: "乾燥にんにく", price: 560 },
  { id: "oribu", name: "グリーンオリーブ", price: 760 },
  { id: "painapuru", name: "畑パイナップル", price: 980 },
  { id: "piman", name: "肉厚ピーマン", price: 340 },
  { id: "sakuranbo", name: "光沢さくらんぼ", price: 1380 },
  { id: "tamanegi", name: "白玉ねぎ", price: 330 },
  { id: "tomato", name: "露地トマト", price: 420 },
  { id: "tougarasi", name: "赤とうがらし", price: 360 },
  { id: "toumorokosi", name: "とうもろこし", price: 580 },
  { id: "yakiimo", name: "紅やきいも", price: 640 },
  { id: "koubebeef", name: "神戸ビーフ", price: 4800 },
  { id: "matuzakausi", name: "松坂牛", price: 3600 },
  { id: "oumigyu", name: "近江牛", price: 4600 },
  { id: "shatoburian", name: "シャトーブリアン", price: 7000 },
  { id: "kinkaton", name: "金華豚", price: 7000 },
  { id: "angasubeef", name: "アンガスビーフ", price: 3000 },
  { id: "honmaguro", name: "本マグロ", price: 15000 },
  { id: "hugu", name: "フグ", price: 8000 },
  { id: "awabi", name: "アワビ", price: 10000 },
  { id: "iseebi", name: "伊勢海老", price: 15000 },
  { id: "hamo", name: "ハモ", price: 9000 },
  { id: "samon", name: "サーモン", price: 9000 },
  { id: "yukata-black", name: "Royal Dining 浴衣 Black Crown", price: 17800 },
  { id: "yukata-gold", name: "Royal Dining 浴衣 Gold Feast", price: 18800 },
  { id: "sweat-white", name: "Royal Dining Hoodie Set White", price: 14800 },
  { id: "tee-white", name: "Royal Dining Tee & Shorts White", price: 9800 },
  { id: "sweat-black", name: "Royal Dining Hoodie Set Black", price: 14800 },
  { id: "dispense-corn", name: "朝採りとうもろこし", price: 640 },
  { id: "dispense-potato-cut", name: "カット新じゃが", price: 460 },
  { id: "dispense-cucumber", name: "朝露きゅうり", price: 360 },
  { id: "dispense-tomato-sliced", name: "雫トマト", price: 520 },
  { id: "dispense-eggplant", name: "艶黒なす", price: 420 },
  { id: "dispense-baked-sweet-potato", name: "蜜焼き芋", price: 720 },
  { id: "dispense-potato-whole", name: "丸ごとじゃがいも", price: 440 },
  { id: "dispense-cherry-branch", name: "枝付きさくらんぼ", price: 1580 },
  { id: "dispense-onion", name: "甘玉ねぎ", price: 360 },
  { id: "dispense-ginger", name: "黄金しょうが", price: 580 },
  { id: "dispense-garlic", name: "白にんにく", price: 620 },
  { id: "dispense-tomato-basil", name: "バジルトマト", price: 560 },
  { id: "dispense-purple-turnip", name: "紫かぶ", price: 480 },
  { id: "dispense-green-olive", name: "樹上グリーンオリーブ", price: 840 },
  { id: "dispense-carrot", name: "雫にんじん", price: 420 },
  { id: "dispense-green-paprika", name: "畑グリーンパプリカ", price: 520 },
  { id: "dispense-avocado-toast", name: "完熟アボカド", price: 780 },
  { id: "dispense-red-chili", name: "赤とうがらし", price: 390 },
  { id: "dispense-cabbage", name: "高原キャベツ", price: 460 },
  { id: "dispense-edamame", name: "枝付きえだまめ", price: 560 },
  { id: "dispense-red-apple", name: "雫りんご", price: 380 },
  { id: "dispense-green-apple-tree", name: "青空青りんご", price: 420 },
  { id: "dispense-grape-vine", name: "樹上ぶどう", price: 980 },
  { id: "dispense-lemon-tree", name: "枝付きレモン", price: 480 },
  { id: "dispense-japanese-pear", name: "洋梨", price: 620 },
  { id: "dispense-kiwi-tree", name: "樹上キウイ", price: 540 },
  { id: "dispense-orange-tree", name: "完熟オレンジ", price: 560 },
  { id: "dispense-melon-vine", name: "畑メロン", price: 1680 },
  { id: "dispense-watermelon-vine", name: "露地スイカ", price: 1280 },
  { id: "dispense-strawberry-field", name: "畑いちご", price: 880 },
  { id: "dispense-blueberry", name: "朝露ブルーベリー", price: 760 },
  { id: "dispense-banana", name: "房バナナ", price: 360 },
  { id: "dispense-lime", name: "グリーンライム", price: 420 },
  { id: "dispense-pineapple", name: "畑パイナップル", price: 980 },
  { id: "dispense-coconut", name: "生ココナッツ", price: 980 },
  { id: "dispense-rice", name: "炊きたて白米", price: 1280 },
  { id: "dispense-egg", name: "平飼いたまご", price: 680 },
  { id: "dispense-chicken", name: "ハーブ鶏むね肉", price: 980 },
  { id: "dispense-black-truffle", name: "黒トリュフ", price: 3200 },
  { id: "dispense-matsutake", name: "桐箱松茸", price: 6800 },
  { id: "dispense-milk", name: "牧場ミルク", price: 420 },
  { id: "dispense-orange-juice", name: "オレンジジュース", price: 520 },
  { id: "dispense-apple-juice", name: "りんごジュース", price: 540 },
  { id: "dispense-grape-juice", name: "ぶどうジュース", price: 680 },
  { id: "dispense-mango-juice", name: "マンゴージュース", price: 720 },
  { id: "dispense-strawberry-juice", name: "いちごジュース", price: 680 },
  { id: "dispense-pineapple-juice", name: "パイナップルジュース", price: 680 },
  { id: "dispense-watermelon-juice", name: "スイカジュース", price: 620 },
  { id: "dispense-mixed-berry-juice", name: "ミックスベリージュース", price: 760 },
  { id: "dispense-melon-juice", name: "メロンジュース", price: 780 },
  { id: "dispense-beef-steak", name: "赤身ステーキ", price: 2400 },
];

export const getProductById = (id: string) => {
  return products.find((product) => product.id === id);
};
